Repository AY2223S2-CS2103T-W15-2/tp, pull requests merged in 2023-04, with the labels that each got.

#268 Fixes quantity field, initial PnL values, success message
  src/main/java/trackr/logic/LogicManager.java
  src/main/java/trackr/logic/commands/EditItemCommand.java
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/model/menu/ItemPrice.java
  src/main/java/trackr/model/menu/ItemSellingPrice.java
  src/main/java/trackr/model/menu/MenuItem.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderQuantity.java
  src/main/java/trackr/model/order/OrderUtil.java
  src/main/java/trackr/model/util/SampleDataUtil.java
  src/main/java/trackr/storage/JsonAdaptedOrder.java
  src/main/java/trackr/ui/MainWindow.java
  src/main/java/trackr/ui/cards/OrderCard.java
  src/main/java/trackr/ui/cards/SummarisedOrderCard.java
  src/main/java/trackr/ui/dashboard/HomeView.java
  src/main/java/trackr/ui/dashboard/TabPanel.java
  src/test/data/JsonSerializableTrackrTest/typicalOrdersTrackr.json
  src/test/java/trackr/logic/commands/FindOrderCommandTest.java
  src/test/java/trackr/logic/parser/AddOrderCommandParserTest.java
  src/test/java/trackr/model/OrderListTest.java
  src/test/java/trackr/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/trackr/model/order/OrderQuantityTest.java
  src/test/java/trackr/model/order/UniqueOrderListTest.java
  src/test/java/trackr/storage/JsonAdaptedOrderTest.java
  src/test/java/trackr/testutil/InvalidMenuItem.java
  src/test/java/trackr/testutil/MenuItemBuilder.java
  src/test/java/trackr/testutil/OrderBuilder.java
  src/test/java/trackr/testutil/TypicalMenuItems.java
  src/test/java/trackr/testutil/TypicalOrders.java
Labels: priority.High

#267 Update and Fix User Guide
  docs/UserGuide.md
  docs/_sass/minima/custom-variables.scss
  docs/images/ug/DataTabUILabeled.png
  docs/images/ug/HelpMessage.png
  docs/images/ug/HomePageUI.png
  docs/images/ug/HomePageUILabeled.png
  docs/images/ug/MenuCardLabeled.png
  docs/images/ug/OrderCardLabeled.png
  docs/images/ug/SupplierCardLabeled.png
  docs/images/ug/TaskCardLabeled.png
  docs/images/ug/ValidCsvFile.png
Labels: type.Documentation

#273 Correct error messages
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/model/commons/Status.java
  src/main/java/trackr/model/menu/ItemName.java
  src/main/java/trackr/model/order/OrderDeadline.java
  src/main/java/trackr/model/order/OrderName.java
  src/main/java/trackr/model/order/OrderStatus.java
  src/main/java/trackr/model/person/PersonName.java
  src/main/java/trackr/model/task/TaskDeadline.java
  src/main/java/trackr/model/task/TaskName.java
  src/main/java/trackr/model/task/TaskStatus.java
  src/main/java/trackr/storage/JsonAdaptedMenuItem.java
  src/main/java/trackr/storage/JsonAdaptedTask.java
Labels: severity.Medium, type.FunctionalityBug

#272 Update and fix Order related bugs
  docs/UserGuide.md
  src/main/java/trackr/logic/commands/EditItemCommand.java
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/order/AddOrderCommandParser.java
  src/main/java/trackr/model/commons/Deadline.java
  src/main/java/trackr/model/order/OrderContainsKeywordsPredicate.java
  src/test/java/trackr/logic/parser/AddTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/EditOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/EditTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/FindOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/FindTaskCommandParserTest.java
Labels: priority.Medium, severity.Medium

#282 Update PPP
  docs/team/chongweiguan.md
Labels: priority.Low, type.Documentation

#276 Update UG
  docs/UserGuide.md
Labels: priority.Low, type.Documentation

#287 Add test for menu commands and DeleteOrderCommandParser, add javadocs and maintain code quality
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/logic/parser/order/DeleteOrderCommandParser.java
  src/main/java/trackr/model/Model.java
  src/main/java/trackr/model/ObservableTabIndex.java
  src/main/java/trackr/model/item/UniqueItemList.java
  src/main/java/trackr/model/menu/ItemPrice.java
  src/main/java/trackr/model/menu/ItemProfit.java
  src/main/java/trackr/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/trackr/model/order/OrderQuantity.java
  src/main/java/trackr/model/order/OrderStatus.java
  src/main/java/trackr/model/order/OrderUtil.java
  src/main/java/trackr/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/trackr/storage/JsonAdaptedTag.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/parser/AddMenuItemCommandParserTest.java
  src/test/java/trackr/logic/parser/DeleteMenuItemCommandParserTest.java
  src/test/java/trackr/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/EditMenuItemCommandParserTest.java
  src/test/java/trackr/logic/parser/FindMenuItemCommandParserTest.java
  src/test/java/trackr/testutil/MenuItemDescriptorBuilder.java
Labels: priority.Medium

#293 Update DG
  docs/DeveloperGuide.md
  docs/images/CorruptedData.png
  docs/images/CorruptedOrderList.png
  docs/img.png
Labels: priority.Low, type.Documentation

#301 Update code ownership
  docs/team/chongweiguan.md
  src/main/java/trackr/MainApp.java
  src/main/java/trackr/logic/Logic.java
  src/main/java/trackr/logic/LogicManager.java
  src/main/java/trackr/logic/commands/UploadCsvCommand.java
  src/main/java/trackr/logic/commands/order/AddOrderCommand.java
  src/main/java/trackr/logic/commands/order/DeleteOrderCommand.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/logic/parser/UploadCsvCommandParser.java
  src/main/java/trackr/logic/parser/order/AddOrderCommandParser.java
  src/main/java/trackr/logic/parser/order/DeleteOrderCommandParser.java
  src/main/java/trackr/model/Model.java
  src/main/java/trackr/model/ModelManager.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/trackr/model/order/OrderDescriptor.java
  src/main/java/trackr/model/order/OrderQuantity.java
  src/main/java/trackr/storage/JsonAdaptedOrder.java
  src/main/java/trackr/storage/JsonSerializableTrackr.java
  src/main/java/trackr/storage/JsonTrackrStorage.java
  src/main/java/trackr/storage/StorageManager.java
  src/main/java/trackr/ui/MainWindow.java
  src/test/java/trackr/logic/LogicManagerTest.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/UploadCsvCommandTest.java
  src/test/java/trackr/logic/commands/order/DeleteOrderCommandTest.java
  src/test/java/trackr/logic/parser/AddOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/ParserUtilTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/logic/parser/UploadCsvCommandParserTest.java
  src/test/java/trackr/model/ModelManagerTest.java
  src/test/java/trackr/model/OrderListTest.java
  src/test/java/trackr/model/order/OrderDeadlineTest.java
  src/test/java/trackr/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/trackr/model/order/OrderNameTest.java
  src/test/java/trackr/model/order/OrderQuantityTest.java
  src/test/java/trackr/model/order/OrderStatusTest.java
  src/test/java/trackr/model/order/UniqueOrderListTest.java
  src/test/java/trackr/model/person/CustomerTest.java
  src/test/java/trackr/storage/JsonAdaptedOrderTest.java
  src/test/java/trackr/storage/JsonSerializableTrackrTest.java
  src/test/java/trackr/testutil/CustomerBuilder.java
  src/test/java/trackr/testutil/OrderBuilder.java
  src/test/java/trackr/testutil/OrderListBuilder.java
  src/test/java/trackr/testutil/OrderPredicateBuilder.java
  src/test/java/trackr/testutil/OrderUtil.java
  src/test/java/trackr/testutil/TestUtil.java
  src/test/java/trackr/testutil/TypicalCustomer.java
  src/test/java/trackr/testutil/TypicalOrders.java
Labels: priority.High
