Repository AY2223S2-CS2103T-W15-2/tp, pull requests merged in 2023-03, with the labels that each got.

#81 Basic UI implementation
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, severity.High

#83 Removed remains of AddressBook to Trackr
  docs/UserGuide.md
Labels: priority.High

#84 Updates `Ui.png`
  docs/images/Ui.png
Labels: severity.Low

#85 Update format of user stories in DG
  docs/DeveloperGuide.md
Labels: type.Enhancement, priority.Low

#86 Update user guide format for 'Features'
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#89 Create Task class and task field classes
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/model/ReadOnlyTaskList.java
  src/main/java/trackr/model/TaskList.java
  src/main/java/trackr/model/task/Task.java
  src/main/java/trackr/model/task/TaskDeadline.java
  src/main/java/trackr/model/task/TaskName.java
  src/main/java/trackr/model/task/TaskStatus.java
  src/main/java/trackr/model/task/UniqueTaskList.java
  src/main/java/trackr/model/task/exceptions/DuplicateTaskException.java
  src/main/java/trackr/model/task/exceptions/TaskNotFoundException.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/model/TaskListTest.java
  src/test/java/trackr/model/task/TaskDeadlineTest.java
  src/test/java/trackr/model/task/TaskNameTest.java
  src/test/java/trackr/model/task/TaskStatusTest.java
  src/test/java/trackr/model/task/TaskTest.java
  src/test/java/trackr/model/task/UniqueTaskListTest.java
  src/test/java/trackr/testutil/TaskBuilder.java
  src/test/java/trackr/testutil/TypicalTasks.java
Labels: type.Task, priority.Medium, user.Tasks

#90 Fix user case bugs
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Low, severity.Low

#97 Add "Add Task feature", update UI to show tasks added and add EditTaskCommand class
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/LogicManager.java
  src/main/java/trackr/logic/commands/AddTaskCommand.java
  src/main/java/trackr/logic/commands/EditTaskCommand.java
  src/main/java/trackr/logic/parser/AddTaskCommandParser.java
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/model/Model.java
  src/main/java/trackr/model/task/TaskStatus.java
  src/main/java/trackr/ui/MainWindow.java
  src/main/java/trackr/ui/TaskCard.java
  src/main/java/trackr/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/trackr/logic/LogicManagerTest.java
  src/test/java/trackr/logic/commands/AddTaskCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/AddTaskCommandTest.java
  src/test/java/trackr/logic/commands/CommandResultTest.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/EditTaskCommandTest.java
  src/test/java/trackr/logic/commands/EditTaskDescriptorTest.java
  src/test/java/trackr/logic/parser/AddTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/ParserUtilTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/model/ModelManagerTest.java
  src/test/java/trackr/model/TaskListTest.java
  src/test/java/trackr/model/task/TaskDeadlineTest.java
  src/test/java/trackr/model/task/TaskNameTest.java
  src/test/java/trackr/model/task/TaskStatusTest.java
  src/test/java/trackr/model/task/UniqueTaskListTest.java
  src/test/java/trackr/testutil/EditTaskDescriptorBuilder.java
  src/test/java/trackr/testutil/TaskBuilder.java
  src/test/java/trackr/testutil/TaskUtil.java
  src/test/java/trackr/testutil/TypicalIndexes.java
Labels: type.Task, priority.Medium, user.Tasks

#99 Implement Edit Task Feature and relevant test cases
  src/main/java/trackr/logic/parser/EditTaskCommandParser.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/test/java/trackr/logic/parser/EditTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/testutil/TaskUtil.java
Labels: type.Task, priority.Medium, user.Tasks

#102 Add clear task command with tests
  src/main/java/trackr/logic/commands/ClearTaskCommand.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/test/java/trackr/logic/commands/ClearTaskCommandTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
Labels: type.Task, priority.Medium

#100 Added Order Model including class fields
  .gitignore
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/model/OrderList.java
  src/main/java/trackr/model/ReadOnlyOrderList.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderDeadline.java
  src/main/java/trackr/model/order/OrderName.java
  src/main/java/trackr/model/order/OrderNameContainsKeywordPredicate.java
  src/main/java/trackr/model/order/OrderStatus.java
  src/main/java/trackr/model/order/UniqueOrderList.java
  src/main/java/trackr/model/order/customer/Customer.java
  src/main/java/trackr/model/order/customer/CustomerAddress.java
  src/main/java/trackr/model/order/customer/CustomerName.java
  src/main/java/trackr/model/order/customer/CustomerPhone.java
  src/main/java/trackr/model/order/customer/exceptions/CustomerNotFoundException.java
  src/main/java/trackr/model/order/customer/exceptions/DuplicateCustomerException.java
  src/main/java/trackr/model/order/exceptions/DuplicateOrderException.java
  src/main/java/trackr/model/order/exceptions/OrderNotFoundException.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/model/OrderListTest.java
  src/test/java/trackr/model/order/OrderDeadlineTest.java
  src/test/java/trackr/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/trackr/model/order/OrderNameTest.java
  src/test/java/trackr/model/order/OrderStatusTest.java
  src/test/java/trackr/model/order/OrderTest.java
  src/test/java/trackr/model/order/UniqueOrderListTest.java
  src/test/java/trackr/model/order/customer/CustomerAddressTest.java
  src/test/java/trackr/model/order/customer/CustomerNameTest.java
  src/test/java/trackr/model/order/customer/CustomerPhoneTest.java
  src/test/java/trackr/model/order/customer/CustomerTest.java
  src/test/java/trackr/testutil/CustomerBuilder.java
  src/test/java/trackr/testutil/OrderBuilder.java
  src/test/java/trackr/testutil/TypicalCustomer.java
  src/test/java/trackr/testutil/TypicalOrders.java
Labels: priority.High, user.Orders

#107 Add order quantity field to order model
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderQuantity.java
  src/main/java/trackr/model/order/customer/CustomerPhone.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/model/order/OrderQuantityTest.java
  src/test/java/trackr/model/order/OrderTest.java
  src/test/java/trackr/model/order/customer/CustomerPhoneTest.java
  src/test/java/trackr/testutil/OrderBuilder.java
  src/test/java/trackr/testutil/TypicalOrders.java
Labels: priority.Medium, user.Orders

#104 Update `Find Task` Command
  src/main/java/trackr/logic/commands/EditTaskCommand.java
  src/main/java/trackr/logic/commands/FindTaskCommand.java
  src/main/java/trackr/logic/parser/EditTaskCommandParser.java
  src/main/java/trackr/logic/parser/FindTaskCommandParser.java
  src/main/java/trackr/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/trackr/model/task/TaskDescriptor.java
  src/main/java/trackr/model/task/TaskNameContainsKeywordsPredicate.java
  src/test/data/JsonSerializableTrackrTest/typicalTasksTrackr.json
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/EditTaskCommandTest.java
  src/test/java/trackr/logic/commands/EditTaskDescriptorTest.java
  src/test/java/trackr/logic/commands/FindTaskCommandTest.java
  src/test/java/trackr/logic/parser/EditTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/FindTaskCommandParserTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/model/ModelManagerTest.java
  src/test/java/trackr/model/task/TaskContainsKeywordsPredicateTest.java
  src/test/java/trackr/model/task/TaskNameContainsKeywordsPredicateTest.java
  src/test/java/trackr/testutil/EditTaskDescriptorBuilder.java
  src/test/java/trackr/testutil/TaskDescriptorBuilder.java
  src/test/java/trackr/testutil/TaskPredicateBuilder.java
  src/test/java/trackr/testutil/TaskUtil.java
  src/test/java/trackr/testutil/TypicalTasks.java
Labels: type.Task, priority.Medium

#115 Add UI display for Order
  src/main/java/trackr/ui/MainWindow.java
  src/main/java/trackr/ui/OrderCard.java
  src/main/java/trackr/ui/OrderListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
Labels: type.Enhancement, priority.High, user.Orders

#112 Minor tweaks for Ui
  src/main/java/trackr/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SupplierListPanel.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: type.Enhancement, priority.Medium

#113 Improve coverage by adding tests
  src/test/java/trackr/AppParametersTest.java
  src/test/java/trackr/logic/LogicManagerTest.java
  src/test/java/trackr/model/SupplierListTest.java
  src/test/java/trackr/model/UserPrefsTest.java
  src/test/java/trackr/model/supplier/AddressTest.java
  src/test/java/trackr/model/supplier/EmailTest.java
  src/test/java/trackr/model/supplier/NameTest.java
  src/test/java/trackr/model/supplier/PhoneTest.java
  src/test/java/trackr/model/supplier/UniqueSupplierListTest.java
  src/test/java/trackr/model/tag/TagTest.java
  src/test/java/trackr/model/task/UniqueTaskListTest.java
Labels: priority.Low, severity.VeryLow, user.Misc

#120 Add Order and Delete Order command
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/LogicManager.java
  src/main/java/trackr/logic/commands/AddOrderCommand.java
  src/main/java/trackr/logic/commands/DeleteOrderCommand.java
  src/main/java/trackr/logic/parser/AddOrderCommandParser.java
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/logic/parser/DeleteOrderCommandParser.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/trackr/model/order/OrderDescriptor.java
  src/main/java/trackr/model/order/OrderNameContainsKeywordPredicate.java
  src/test/java/trackr/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/AddOrderCommandTest.java
  src/test/java/trackr/logic/commands/AddSupplierCommandTest.java
  src/test/java/trackr/logic/commands/AddTaskCommandTest.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/DeleteOrderCommandTest.java
  src/test/java/trackr/logic/parser/AddOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/DeleteOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/ParserUtilTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/trackr/testutil/OrderPredicateBuilder.java
  src/test/java/trackr/testutil/OrderUtil.java
  src/test/java/trackr/testutil/TestUtil.java
Labels: type.Story, priority.Medium, user.Orders

#119 Refractor `clear` and `list` command for supplier
  src/main/java/trackr/logic/commands/ClearSupplierCommand.java
  src/main/java/trackr/logic/commands/ListSupplierCommand.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/test/java/trackr/logic/LogicManagerTest.java
  src/test/java/trackr/logic/commands/ClearSupplierCommandTest.java
  src/test/java/trackr/logic/commands/EditCommandTest.java
  src/test/java/trackr/logic/commands/EditSupplierCommandTest.java
  src/test/java/trackr/logic/commands/EditTaskCommandTest.java
  src/test/java/trackr/logic/commands/ListSupplierCommandTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
Labels: priority.Medium, user.Suppliers

#132 Add `clear` and `list` command for orders
  src/main/java/trackr/logic/commands/ClearOrderCommand.java
  src/main/java/trackr/logic/commands/ListOrderCommand.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/test/java/trackr/logic/commands/ClearOrderCommandTest.java
  src/test/java/trackr/logic/commands/ListOrderCommandTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
Labels: priority.Medium, user.Orders

#134 Implement Find Order Command and Edit Order Command
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/commands/EditOrderCommand.java
  src/main/java/trackr/logic/commands/FindOrderCommand.java
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/logic/parser/EditOrderCommandParser.java
  src/main/java/trackr/logic/parser/FindOrderCommandParser.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/model/OrderList.java
  src/main/java/trackr/model/order/OrderStatus.java
  src/main/java/trackr/model/order/customer/Customer.java
  src/main/java/trackr/model/order/exceptions/OrderNotFoundException.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/EditOrderCommandTest.java
  src/test/java/trackr/logic/commands/EditOrderDescriptorTest.java
  src/test/java/trackr/logic/commands/EditTaskCommandTest.java
  src/test/java/trackr/logic/parser/EditOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/EditTaskCommandParserTest.java
  src/test/java/trackr/testutil/OrderDescriptorBuilder.java
  src/test/java/trackr/testutil/TypicalOrders.java
Labels: priority.High, user.Orders

#137 Updates Ui component of DG and UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High

#140 Fix Test Cases for Edit and Find Order Commands
  src/main/java/trackr/logic/parser/FindOrderCommandParser.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/FindOrderCommandTest.java
  src/test/java/trackr/logic/parser/EditOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/FindOrderCommandParserTest.java
Labels: type.Bug, priority.High, severity.High, user.Orders

#144 Updates `DeveloperGuide.md`
  docs/DeveloperGuide.md
Labels: priority.High, user.Misc

#150 Update DG (Model - Task and Person)
  docs/DeveloperGuide.md
  docs/diagrams/ItemClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ItemClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/TaskClassDiagram.png
Labels: priority.Medium, user.Misc

#152 Update DG (Storage & User stories)
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.Medium

#151 Fix error in SupplierListCard
  src/main/resources/view/SupplierListCard.fxml
Labels: type.Bug, priority.High, severity.High, user.Suppliers

#156 Enable assertions
  build.gradle
Labels: priority.Low

#158 Updates `UiClassDiagram` to clean up and to svg format
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagram.svg
Labels: priority.High

#159 Fix DG (Storage) & Update DG Implementation
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/StorageClassDiagram.png
  docs/images/StorageClassDiagram.svg
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState0.svg
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState1.svg
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState2.svg
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState3.svg
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState4.svg
  docs/images/UndoRedoState5.png
  docs/images/UndoRedoState5.svg
  docs/images/UndoSequenceDiagram.png
  docs/images/UndoSequenceDiagram.svg
Labels: type.Task, priority.Medium, user.Misc

#157 Fix DG UML (Item, Person, Model)
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/ItemClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureDiagram.svg
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.svg
  docs/images/ComponentManagers.png
  docs/images/ComponentManagers.svg
  docs/images/ItemClassDiagram.png
  docs/images/ItemClassDiagram.svg
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassDiagram.svg
  docs/images/PersonClassDiagram.png
  docs/images/PersonClassDiagram.svg
  docs/images/TaskClassDiagram.png
  docs/images/TaskClassDiagram.svg
  docs/tutorials/TracingCode.md
  src/main/java/trackr/MainApp.java
  src/main/java/trackr/storage/StorageManager.java
Labels: priority.Medium, user.Misc

#155 Update DG(Menu and Order)
  docs/DeveloperGuide.md
  docs/diagrams/MenuClassDiagram.puml
  docs/diagrams/OrderClassDiagram.puml
  docs/images/MenuClassDiagram.svg
  docs/images/OrderClassDiagram.svg
Labels: type.Task, priority.Medium

#166 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/MenuClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/OrderClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.svg
  docs/images/BetterModelClassDiagram.png
  docs/images/ComponentManagers.svg
  docs/images/FindCommandActivityDiagram.svg
  docs/images/ItemClassDiagram.svg
  docs/images/MenuClassDiagram.svg
  docs/images/ModelClassDiagram.svg
  docs/images/OrderClassDiagram.svg
  docs/images/PersonClassDiagram.svg
  docs/images/TaskClassDiagram.svg
  docs/images/UiClassDiagram.svg
Labels: priority.Medium

#167 Fix DG ToC
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#168 Update DG activity diagram - AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/images/AddCommandActivityDiagram.svg
Labels: type.Task, priority.Medium

#170 Removed forced assertion in MainApp
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/images/FindCommandActivityDiagram.svg
  src/main/java/trackr/MainApp.java
Labels: type.Bug, priority.High

#154 Update DG (Logic)
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.svg
  docs/images/LogicClassDiagram.png
  docs/images/LogicClassDiagram.svg
  docs/images/ParserClasses.png
  docs/images/ParserClasses.svg
Labels: priority.Medium, user.Misc

#173 Add Edit Command Implementation to DG (Implementation)
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/CommitActivityDiagram.svg
  docs/images/EditCommandActivityDiagram.svg
Labels: type.Task, priority.Medium, user.Misc

#175 Update DG - List Command
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium, user.Misc

#174 Minor cosmetic changes to activity diagram
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/images/EditCommandActivityDiagram.svg
Labels: type.Task, priority.Low, user.Misc

#179 Updates Ui
  src/main/java/trackr/logic/commands/TabCommand.java
  src/main/java/trackr/logic/commands/order/AddOrderCommand.java
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/ui/HomeView.java
  src/main/java/trackr/ui/MainWindow.java
  src/main/java/trackr/ui/cards/OrderCard.java
  src/main/java/trackr/ui/cards/SummarisedOrderCard.java
  src/main/java/trackr/ui/cards/SupplierCard.java
  src/main/java/trackr/ui/cards/TaskCard.java
  src/main/java/trackr/ui/dashboard/HomeView.java
  src/main/java/trackr/ui/dashboard/TabPanel.java
  src/main/java/trackr/ui/listpanels/OrderListPanel.java
  src/main/java/trackr/ui/listpanels/SummarisedOrderListPanel.java
  src/main/java/trackr/ui/listpanels/SupplierListPanel.java
  src/main/java/trackr/ui/listpanels/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HomeDashboard.fxml
  src/main/resources/view/HomeView.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SummarisedOrderCard.fxml
  src/main/resources/view/SummarisedOrderListPanel.fxml
  src/main/resources/view/TabPanel.fxml
Labels: priority.High

#185 Update UG (Upload csv)
  docs/UserGuide.md
  docs/images/CsvFileFormat.png
Labels: priority.Medium, severity.Medium, user.Misc

#183 Update UG (Sort Task Feature)
  docs/UserGuide.md
Labels: type.Task, priority.Medium, user.Misc

#180 Implement sort task feature
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/Logic.java
  src/main/java/trackr/logic/commands/task/SortTasksCommand.java
  src/main/java/trackr/logic/parser/CliSyntax.java
  src/main/java/trackr/logic/parser/CriteriaEnum.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/logic/parser/task/SortTasksCommandParser.java
  src/main/java/trackr/model/Model.java
  src/main/java/trackr/model/ModelManager.java
  src/main/java/trackr/model/commons/Deadline.java
  src/main/java/trackr/model/commons/Name.java
  src/main/java/trackr/model/commons/Status.java
  src/main/java/trackr/model/item/ItemList.java
  src/main/java/trackr/model/item/UniqueItemList.java
  src/main/java/trackr/model/task/SortTasksComparator.java
  src/main/java/trackr/model/task/Task.java
  src/main/java/trackr/model/util/SampleDataUtil.java
  src/main/java/trackr/storage/JsonAdaptedTask.java
  src/main/java/trackr/ui/dashboard/TabPanel.java
  src/test/data/JsonSerializableTrackrTest/duplicateTaskTrackr.json
  src/test/data/JsonSerializableTrackrTest/invalidTaskTrackr.json
  src/test/data/JsonSerializableTrackrTest/typicalTasksTrackr.json
  src/test/data/JsonTrackrStorageTest/invalidAndValidTaskTrackr.json
  src/test/data/JsonTrackrStorageTest/invalidTaskTrackr.json
  src/test/java/trackr/logic/commands/SortTasksCommandTest.java
  src/test/java/trackr/storage/JsonAdaptedTaskTest.java
  src/test/java/trackr/testutil/TestUtil.java
Labels: type.Task, priority.Medium, user.Tasks

#178 Upload csv file feature
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/commands/Command.java
  src/main/java/trackr/logic/commands/UploadCsvCommand.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/logic/parser/UploadCsvCommandParser.java
  src/main/java/trackr/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/trackr/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/AddOrderCommandTest.java
  src/test/java/trackr/logic/commands/AddSupplierCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/AddTaskCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/ClearOrderCommandTest.java
  src/test/java/trackr/logic/commands/ClearSupplierCommandTest.java
  src/test/java/trackr/logic/commands/ClearTaskCommandTest.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/commands/DeleteOrderCommandTest.java
  src/test/java/trackr/logic/commands/DeleteSupplierCommandTest.java
  src/test/java/trackr/logic/commands/DeleteTaskCommandTest.java
  src/test/java/trackr/logic/commands/EditOrderCommandTest.java
  src/test/java/trackr/logic/commands/EditSupplierCommandTest.java
  src/test/java/trackr/logic/commands/EditTaskCommandTest.java
  src/test/java/trackr/logic/commands/ExitCommandTest.java
  src/test/java/trackr/logic/commands/FindOrderCommandTest.java
  src/test/java/trackr/logic/commands/FindSupplierCommandTest.java
  src/test/java/trackr/logic/commands/FindTaskCommandTest.java
  src/test/java/trackr/logic/commands/HelpCommandTest.java
  src/test/java/trackr/logic/commands/ListOrderCommandTest.java
  src/test/java/trackr/logic/commands/ListSupplierCommandTest.java
  src/test/java/trackr/logic/commands/ListTaskCommandTest.java
  src/test/java/trackr/logic/commands/UploadCsvCommandTest.java
  src/test/java/trackr/logic/parser/UploadCsvCommandParserTest.java
Labels: type.Story, priority.Medium, severity.Medium

#187 Refractor customer
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/order/AddOrderCommandParser.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderDescriptor.java
  src/main/java/trackr/model/order/customer/Customer.java
  src/main/java/trackr/model/order/customer/CustomerAddress.java
  src/main/java/trackr/model/order/customer/CustomerName.java
  src/main/java/trackr/model/order/customer/CustomerPhone.java
  src/main/java/trackr/model/order/customer/exceptions/CustomerNotFoundException.java
  src/main/java/trackr/model/order/customer/exceptions/DuplicateCustomerException.java
  src/main/java/trackr/model/person/Customer.java
  src/main/java/trackr/model/util/SampleDataUtil.java
  src/main/java/trackr/storage/JsonAdaptedOrder.java
  src/main/java/trackr/ui/cards/OrderCard.java
  src/main/java/trackr/ui/cards/SummarisedOrderCard.java
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/logic/parser/EditOrderCommandParserTest.java
  src/test/java/trackr/logic/parser/ParserUtilTest.java
  src/test/java/trackr/model/order/customer/CustomerNameTest.java
  src/test/java/trackr/model/order/customer/CustomerPersonAddressTest.java
  src/test/java/trackr/model/order/customer/CustomerPersonPhoneTest.java
  src/test/java/trackr/model/supplier/CustomerTest.java
  src/test/java/trackr/storage/JsonAdaptedOrderTest.java
  src/test/java/trackr/testutil/CustomerBuilder.java
  src/test/java/trackr/testutil/OrderBuilder.java
  src/test/java/trackr/testutil/OrderDescriptorBuilder.java
  src/test/java/trackr/testutil/OrderPredicateBuilder.java
  src/test/java/trackr/testutil/OrderUtil.java
  src/test/java/trackr/testutil/TypicalCustomer.java
Labels: priority.Medium

#189 Fix implementation bug - can take in decimal and round off calculation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/trackr/model/menu/ItemCost.java
  src/main/java/trackr/model/menu/ItemPrice.java
  src/main/java/trackr/model/menu/ItemProfit.java
  src/main/java/trackr/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.High, severity.Low, user.Menu

#182 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
Labels: priority.Medium

#192 Implement sort order feature
  src/main/java/trackr/commons/core/Messages.java
  src/main/java/trackr/logic/commands/order/SortOrdersCommand.java
  src/main/java/trackr/logic/commands/task/SortTasksCommand.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/TrackrParser.java
  src/main/java/trackr/logic/parser/order/SortOrdersCommandParser.java
  src/main/java/trackr/model/Model.java
  src/main/java/trackr/model/ModelManager.java
  src/main/java/trackr/model/commons/Status.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/trackr/model/order/OrderDeadline.java
  src/main/java/trackr/model/order/OrderName.java
  src/main/java/trackr/model/order/OrderStatus.java
  src/main/java/trackr/model/order/SortOrdersComparator.java
  src/main/java/trackr/model/task/Task.java
  src/main/java/trackr/model/task/TaskStatus.java
  src/main/java/trackr/model/util/SampleDataUtil.java
  src/main/java/trackr/storage/JsonAdaptedOrder.java
  src/main/java/trackr/ui/cards/OrderCard.java
  src/main/java/trackr/ui/cards/SummarisedOrderCard.java
  src/test/data/JsonSerializableTrackrTest/duplicateOrderTrackr.json
  src/test/data/JsonSerializableTrackrTest/invalidOrderTrackr.json
  src/test/data/JsonSerializableTrackrTest/typicalOrdersTrackr.json
  src/test/java/trackr/logic/commands/CommandTestUtil.java
  src/test/java/trackr/model/order/OrderDeadlineTest.java
  src/test/java/trackr/model/order/OrderNameTest.java
  src/test/java/trackr/model/order/OrderStatusTest.java
  src/test/java/trackr/storage/JsonAdaptedOrderTest.java
  src/test/java/trackr/storage/JsonSerializableTrackrTest.java
  src/test/java/trackr/testutil/OrderUtil.java
  src/test/java/trackr/testutil/TestUtil.java
Labels: type.Enhancement, priority.Medium, user.Orders

#194 Upload CSV - Menu Item
  docs/UserGuide.md
  docs/images/CsvFileFormat.png
  docs/images/ValidCsvFile.png
  src/main/java/trackr/logic/parser/UploadCsvCommandParser.java
  src/main/java/trackr/model/menu/ItemProfit.java
  src/main/java/trackr/model/order/Order.java
Labels: priority.Medium, severity.Medium, user.Misc

#195 Update UG - Upload csv
  docs/UserGuide.md
Labels: priority.Low, severity.Low, user.Misc

#198 Update UG
  docs/UserGuide.md
Labels: priority.Medium

#199 Update menu list and clear command
  docs/UserGuide.md
Labels: priority.High

#197 Couples Order and MenuItem
  docs/images/Ui.png
  src/main/java/trackr/logic/Logic.java
  src/main/java/trackr/logic/LogicManager.java
  src/main/java/trackr/logic/commands/AddItemCommand.java
  src/main/java/trackr/logic/commands/menu/EditMenuItemCommand.java
  src/main/java/trackr/logic/commands/order/AddOrderCommand.java
  src/main/java/trackr/logic/commands/order/EditOrderCommand.java
  src/main/java/trackr/logic/parser/ParserUtil.java
  src/main/java/trackr/logic/parser/menu/AddMenuItemCommandParser.java
  src/main/java/trackr/model/menu/ItemCost.java
  src/main/java/trackr/model/menu/ItemPrice.java
  src/main/java/trackr/model/menu/ItemProfit.java
  src/main/java/trackr/model/menu/ItemSellingPrice.java
  src/main/java/trackr/model/menu/MenuItem.java
  src/main/java/trackr/model/menu/MenuItemDescriptor.java
  src/main/java/trackr/model/order/Order.java
  src/main/java/trackr/model/order/OrderQuantity.java
  src/main/java/trackr/model/order/OrderUtil.java
  src/main/java/trackr/model/person/Customer.java
  src/main/java/trackr/model/util/SampleDataUtil.java
  src/main/java/trackr/storage/JsonAdaptedMenuItem.java
  src/main/java/trackr/ui/dashboard/HomeView.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HomeDashboard.fxml
  src/main/resources/view/MenuListCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/trackr/logic/commands/AddOrderCommandIntegrationTest.java
  src/test/java/trackr/logic/commands/AddOrderCommandTest.java
  src/test/java/trackr/logic/commands/EditOrderCommandTest.java
  src/test/java/trackr/logic/commands/EditOrderDescriptorTest.java
  src/test/java/trackr/logic/parser/TrackrParserTest.java
  src/test/java/trackr/model/OrderListTest.java
  src/test/java/trackr/model/order/OrderTest.java
  src/test/java/trackr/model/order/UniqueOrderListTest.java
  src/test/java/trackr/storage/JsonAdaptedOrderTest.java
  src/test/java/trackr/storage/JsonSerializableTrackrTest.java
  src/test/java/trackr/testutil/MenuItemBuilder.java
Labels: type.Enhancement, priority.Medium, user.Orders

#201 Update UG Summary
  docs/UserGuide.md
Labels: priority.High
