Repository AY2223S2-CS2103T-W15-2/tp, pull requests merged in 2023-02, with the labels that each got.

#59 Updates `Ui.png` in `docs/images`
  docs/images/Ui.png
Labels: type.Task, priority.Medium, pr.dev

#58 Update Admin Information
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/changgittyhub.png
  docs/team/changgittyhub.md
Labels: type.Task, priority.Medium, pr.dev

#60 Update Admin Information (Bug)
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/changgittyhub.png
  docs/team/changgittyhub.md
Labels: type.Task, priority.High, pr.master

#62 Fix Bug PPP(Bug)
  docs/team/changgittyhub.md
Labels: type.Task, severity.High, pr.master

#53 Update UG - Task
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Task, priority.Medium, pr.dev

#51 Update site-wide settings
  docs/_config.yml
Labels: type.Task, priority.Medium, pr.dev

#45 Update personal details and create individual PPP (Style)
  docs/AboutUs.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/liumc-sg.png
  docs/team/liumc-sg.md
Labels: priority.Medium, user.Tasks, pr.dev

#52 Update site-wide settings (Bug)
  docs/_config.yml
Labels: type.Task, priority.Medium

#49 Update README.md
  README.md
Labels: type.Task, priority.Medium

#47 Update UG - Supplier, Task
  docs/UserGuide.md
Labels: priority.Medium, user.Tasks

#64 Update index.md
  docs/AboutUs.md
  docs/index.md
Labels: type.Task, priority.Medium

#65 Update `AboutUs.md`, added picture, update PPP
  docs/AboutUs.md
  docs/images/hmuumyatmoe.png
  docs/team/hmuumyatmoe.md
Labels: type.Task, priority.Medium

#70 Update DG (Glossary & User stories)
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#72 Updated UG for remaining supplier commands
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#73 Update NFR
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium
